container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - "aria2c --header 'Host: nl34.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/118033674' --header 'Upgrade-Insecure-Requests: 1' 'https://nl34.seedr.cc/ff_get/603621036/Jumanji.The.Next.Level.2019.720p.WEBRip.x264.AAC-[YTS.MX].mp4?st=sISrSOLNHddN7DTyWIfNnw&e=1583175599' --out 'Jumanji.The.Next.Level.2019.720p.WEBRip.x264.AAC-[YTS.MX].mp4'"
    - ffmpeg -i "Jumanji.The.Next.Level.2019.720p.WEBRip.x264.AAC-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Jumanji 1995" Jumanji.The.Next.Level.2019.720p.WEBRip.x265.mp4
  binaries_artifacts:
    path: "Jumanji.The.Next.Level.2019.720p.WEBRip.x265.mp4"

# docker_builder:
#   env:
#     DOCKER_USERNAME: tigefa
#     DOCKER_PASSWORD: ENCRYPTED[f5837087e13403c1483dbeeb520330ccbf20981b99c7f58b409a7adb1f4c16df8ab8aabdb5bf269e639e1759377231e3]
#   build_script: docker build --tag sgng/lubuntu .
#   login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
#   push_script: docker push sgng/lubuntu
