container:
  image: "registry.gitlab.com/tigefa/ffmpeg"
  cpu: 8
  memory: 21

ffmpeg_task:
  timeout_in: 120m
  install_script:
    - apt-get update
    - apt-get dist-upgrade -yqq
    - apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet p7zip p7zip-full zip unzip
    - apt-get install -yqq wget aria2 ffmpeg telnet tree
  test_script:
    - aria2c https://yts.mx/torrent/download/8005116D1B69A5008A823AB0B7ADBB8E4495A16B
    - ffmpeg -i "Bombshell (2019) [720p] [BluRay] [YTS.MX]/Bombshell.2019.720p.BluRay.x264.AAC-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a copy -metadata title="Bombshell 2019" -preset veryfast Bombshell.2019.720p.BluRay.x265.mp4
    - ls -hal
  binaries_artifacts:
    path: "Bombshell.2019.720p.BluRay.x265.mp4"

# docker_builder:
#   env:
#     DOCKER_USERNAME: tigefa
#     DOCKER_PASSWORD: ENCRYPTED[f5837087e13403c1483dbeeb520330ccbf20981b99c7f58b409a7adb1f4c16df8ab8aabdb5bf269e639e1759377231e3]
#   build_script: docker build --tag sgng/lubuntu .
#   login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
#   push_script: docker push sgng/lubuntu
