version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -yqq wget aria2 httpie ffmpeg speedtest-cli telnet lshw tree

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            aria2c 'http://cf-aue1-docker-node-0009.cf-cd.com:32953/download/FONE-100.mp4'
            ffmpeg -i "FONE-100.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="FONE 100" -s 960x540 FONE-100-x265.mp4
            ls -hal
            speedtest --share --secure

      - store_artifacts:
          path: FONE-100-x265.mp4
