version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update -yqq && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git-all p7zip p7zip-full zip unzip
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            apt-get install -yqq nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            wget -qO- https://get.docker.com/ | sh
            docker version
            docker info
            tar -cvf tmp.tar /tmp && curl https://transfer.sh --upload-file tmp.tar

      - run:
          name: Build and push Docker image
          command: |
            docker pull tigefa/bionic
            docker pull tigefa/bionic:i386
            docker pull tigefa/bionic:buildpack
            docker pull tigefa/debian
            docker pull tigefa/dropbox
            docker pull redis
            docker images

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            docker ps
            docker images
            speedtest --share --secure

      - store_artifacts:
          path: $CIRCLE_WORKING_DIRECTORY/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
