version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -yqq nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            aria2c --header 'Host: nl29.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/113950259' --header 'Upgrade-Insecure-Requests: 1' 'https://nl29.seedr.cc/ff_get/583460041/Dark.Waters.2019.720p.BluRay.x264-[YTS.LT].mp4?st=2i3EnnM7FRt62C9FnPBtIA&e=1579450154' --out 'Dark.Waters.2019.720p.BluRay.x264-[YTS.LT].mp4'
            ffmpeg -i "Dark.Waters.2019.720p.BluRay.x264-[YTS.LT].mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Dark Waters 2019" Dark.Waters.2019.720p.BluRay.x265.mp4
            ls -hal
            speedtest --share --secure

      - store_artifacts:
          path: Dark.Waters.2019.720p.BluRay.x265.mp4
