version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -yqq nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            aria2c --header 'Host: doc-0k-8g-docs.googleusercontent.com' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://drive.google.com/uc?id=1IY-HjQ5ChktcCw8biO48zq982G_rXoVK&export=download' --header 'Cookie: AUTH_f14mbjoom8njafno4j2pq8oik9ksa7lg_nonce=iqkv6hjn5m7ek' --header 'Upgrade-Insecure-Requests: 1' 'https://doc-0k-8g-docs.googleusercontent.com/docs/securesc/295bc0gov3oagqv4dejq234vcdd4i3f3/g6cc36bocce0kiog455svclohn191c3b/1578859200000/03287608010741263752/03287608010741263752/1IY-HjQ5ChktcCw8biO48zq982G_rXoVK?e=download&authuser=0&nonce=iqkv6hjn5m7ek&user=03287608010741263752&hash=stj5cie9t5jdcu1imjk540gp4mra2hrc' --out 'Running.Man.E485.200112.720p-NEXT.mp4'
            ffmpeg -i "Running.Man.E485.200112.720p-NEXT.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Running Man Episode 485" -s 960x540 485.mkv
            ls -hal
            speedtest --share --secure

      - store_artifacts:
          path: 485.mkv
