version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update -yqq && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            apt-get install -yqq nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            wget -qO- https://get.docker.com/ | sh
            docker version
            docker info
            tar -cvf tmp.tar /tmp && curl -fsSL https://transfer.sh --upload-file tmp.tar

      - run:
          name: Build and push Docker image
          command: |
            docker pull tigefa/bionic
            docker pull tigefa/dropbox
            docker pull tigefa/cloud-torrent
            docker pull tigefa/torproxy
            docker pull gitlab/gitlab-runner:latest
            docker pull tigefa/bionic:buildpack
            docker images

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            ./gitlab-runner.sh
            curl -sSL https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-64bit-static.tar.xz | tar -C /usr/local/bin --strip 1 -xJf -
            aria2c --seed-time=1 --seed-ratio=1.0 "https://www.dropbox.com/s/dl/4mgt7njv9rr4qcn/Boogeyman.III.2008.1080p.BluRay.H264.AAC-RARBG.mp4"
            docker images
            docker ps
            ffmpeg -i "Boogeyman.III.2008.1080p.BluRay.H264.AAC-RARBG.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Boogeyman III 2008" Boogeyman.III.2008.1080p.BluRay.H265.mp4
            ls -hal
            npm i -g npm
            npm i -g yarn
            npm i -g node-gyp node-pre-gyp
            npm i -g webtorrent-cli
            webtorrent --keep-seeding "magnet:?xt=urn:btih:37654e4c5f9a03ba1970b4ccdb150cf1b94336f7&dn=Mile%2022%20%282018%29%20%5BBluRay%5D%20%5B720p%5D%20%5BYTS.AM%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=https%3A%2F%2Fbittorrent-tracker-nzqtbmlfih.now.sh%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2710%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce"
            docker ps
            docker images
            speedtest --share --secure

      - store_artifacts:
          path: Boogeyman.III.2008.1080p.BluRay.H265.mp4
