version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -yqq nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            aria2c 'http://cf-aue1-docker-node-0009.cf-cd.com:32906/download/SSNI-700.mp4'
            ffmpeg -i "SSNI-700.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="SSNI 700" -s 960x540 SSNI-700-x265.mp4
            ls -hal
            speedtest --share --secure

      - store_artifacts:
          path: SSNI-700-x265.mp4
