version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -y sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -y nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            wget -qO- https://get.docker.com/ | sh
            docker version
            docker info
            tar -cvf tmp.tar /tmp && curl -fsSL https://transfer.sh --upload-file tmp.tar

      - run:
          name: Build and push Docker image
          command: |
            docker pull tigefa/bionic
            docker pull tigefa/dropbox
            docker pull tigefa/cloud-torrent
            docker pull tigefa/torproxy
            docker images

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            aria2c --seed-time=1 --seed-ratio=1.0 "http://cf-azuc-docker-node-0039.az.codefresh.io:32844/download/DTT-034.mp4"
            docker images
            docker ps
            ffmpeg -i "DTT-034.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="DTT-034" -s 960x540 DTT-034.x265.mp4
            ls -hal
            docker ps
            docker images
            speedtest --share --secure

      - store_artifacts:
          path: DTT-034.x265.mp4
