version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -yqq nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            aria2c 'http://cf-aue1-docker-node-0008.cf-cd.com:32884/download/Black%20And%20Blue%20(2019)%20[WEBRip]%20[720p]%20[YTS.LT]/Black.And.Blue.2019.720p.WEBRip.x264-[YTS.LT].mp4'
            ffmpeg -i "Black.And.Blue.2019.720p.WEBRip.x264-[YTS.LT].mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Black and Blue 2019" Black.And.Blue.2019.720p.WEBRip.x265.mp4
            ls -hal
            speedtest --share --secure

      - store_artifacts:
          path: Black.And.Blue.2019.720p.WEBRip.x265.mp4
