version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -yqq nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            aria2c 'http://cf-aue1-docker-node-0008.cf-cd.com:32904/download/xxfhd.com_%E5%8E%9F%E7%89%88%E9%A6%96%E5%8F%91_PPPD-809.mp4' --out 'PPPD-809.mp4'
            ffmpeg -i "PPPD-809.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Hitomi Tanaka PPPD 809" -s 960x540 PPPD-809.x265.mkv
            ls -hal
            speedtest --share --secure

      - store_artifacts:
          path: PPPD-809.x265.mkv
