version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -y sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -y nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - setup_remote_docker

      - run:
          name: Install Docker client
          command: |
            wget -qO- https://get.docker.com/ | sh
            docker version
            docker info

      - run:
          name: Build and push Docker image
          command: |
            docker pull tigefa/bionic
            docker pull tigefa/dropbox
            docker pull tigefa/cloud-torrent
            docker pull tigefa/torproxy
            docker images

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            aria2c --header 'Host: nl29.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/102623966' --header 'Upgrade-Insecure-Requests: 1' 'https://nl29.seedr.cc/ff_get/522394161/Toy.Story.4.2019.720p.BluRay.x264-[YTS.LT].mp4?st=HkEaNmxZW_oFZh_9RYs-Jw&e=1569859254' --out 'Toy.Story.4.2019.720p.BluRay.x264-[YTS.LT].mp4'
            docker images
            docker ps
            ffmpeg -i "Toy.Story.4.2019.720p.BluRay.x264-[YTS.LT].mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Toy Story 4 2019" Toy.Story.4.2019.720p.BluRay.x265.mp4
            ls -hal
            docker ps
            docker images
            speedtest --share --secure

      - store_artifacts:
          path: Toy.Story.4.2019.720p.BluRay.x265.mp4
