version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -yqq nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            aria2c --header 'Host: nl27.seedr.cc' --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' --header 'Accept-Language: id,en-US;q=0.7,en;q=0.3' --referer 'https://www.seedr.cc/files/116034738' --header 'Upgrade-Insecure-Requests: 1' 'https://nl27.seedr.cc/ff_get/594001540/Knives.Out.2019.720p.WEBRip.x264.AAC-[YTS.MX].mp4?st=8bTHa5UotJbL0CoWyI-hiA&e=1581268131' --out 'Knives.Out.2019.720p.WEBRip.x264.AAC-[YTS.MX].mp4'
            ffmpeg -i "Knives.Out.2019.720p.WEBRip.x264.AAC-[YTS.MX].mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Knives Out 2019" Knives.Out.2019.720p.WEBRip.x265.mp4
            ls -hal
            speedtest --share --secure

      - store_artifacts:
          path: Knives.Out.2019.720p.WEBRip.x265.mp4
