version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic:buildpack

    steps:
      - checkout

      - run:
          name: Requirements
          command: |
            apt-get update && apt-get dist-upgrade -yqq && apt-get install -yqq sudo lsb-base lsb-release apt-transport-https ca-certificates software-properties-common dirmngr gnupg gnupg2 wget curl netcat aria2 whois figlet git p7zip p7zip-full zip unzip
            apt-get install -yqq nodejs python-pip python3-pip wget aria2 httpie ffmpeg youtube-dl speedtest-cli telnet lshw tree

      - run:
          name: Butterfly
          command: |
            ulimit -c unlimited
            speedtest --share --secure
            aria2c 'http://cf-aue1-docker-node-0009.cf-cd.com:32946/download/Frozen.2.2019.WEB-DL.x264-FGT/Frozen.2.2019.WEB-DL.x264-FGT.mp4'
            ffmpeg -i "Frozen.2.2019.WEB-DL.x264-FGT.mp4" -threads 16 -c:v libx265 -c:a aac -metadata title="Frozen 2 2019" Frozen.2.2019.WEB-DL.x265-FGT.mp4
            ls -hal
            speedtest --share --secure

      - store_artifacts:
          path: Frozen.2.2019.WEB-DL.x265-FGT.mp4
