name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  runs:
    using: 'docker'
    image: 'ghcr.io/tigefa4u/ffmpeg:alpine'
      args:
      - ffmpeg -version
